{% set version = "6.0" %}

package:
  name: pyyaml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyYAML/PyYAML-{{ version }}.tar.gz
  sha256: 68fb519c14306fec9720a2a5b45bc9f0c8d1b9c72adf45c37baedfcd949c35a2
  patches:
    - 0001-Ensure-we-do-not-end-up-wih-CRLF-line-endings-on-tes.patch
    - 0002-remove-setuptools-use-distutils-py38.patch  # [py<39]

build:
  number: 2
  script:
    {{ set EXTRA_FLAGS = '--global-option="-I%LIBRARY_INC%" --global-option="-L%LIBRARY_LIB%"' if win '--global-option="-I${PREFIX}/include" --global-option="-L${PREFIX}/lib"'}}
    - >-
      {{ PYTHON }} -m pip install --no-deps --ignore-installed .
                                  --global-option="--with-libyaml"
                                  --global-option="build_ext"
                                  {{ EXTRA_FLAGS }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - setuptools
    - yaml
  run:
    - python
    - yaml

test:
  imports:
    - yaml
    - _yaml   # [python_impl == "cpython"]
  commands:
    # temporarily skipping pip check on win and pypy build because of bizarre tqdm issue
    - pip check  # [not (win and python_impl == 'pypy')]
  requires:
    - pip

about:
  home: http://pyyaml.org/wiki/PyYAML
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: YAML parser and emitter for Python
  dev_url: https://github.com/yaml/pyyaml
  doc_url: http://pyyaml.org/wiki/PyYAML

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - ocefpaf
